/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package penjualan_rumah;

import Konfigurasi.Koneksi;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.util.Random;

public class JIPenjualan extends javax.swing.JFrame {

private int Ltersedia, Htanah, Hbangunan, nDp, nPeriode;
private String tipe, area;
String SQL, no_pelanggan;
int kode, RandomB;
char RandomA;

    public JIPenjualan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jNopelanggan = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbArea = new javax.swing.JComboBox<>();
        gambar = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        RBTipe1 = new javax.swing.JRadioButton();
        RBTipe24 = new javax.swing.JRadioButton();
        RBTipe30 = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtHargaBangunan = new javax.swing.JTextField();
        txtLuasAsli = new javax.swing.JTextField();
        txtLuasTersedia = new javax.swing.JTextField();
        txtHarga = new javax.swing.JTextField();
        txtDp = new javax.swing.JTextField();
        txtPeriode = new javax.swing.JTextField();
        txtPpn = new javax.swing.JTextField();
        txtCicilan = new javax.swing.JTextField();
        BProses = new javax.swing.JButton();
        jSimpan = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        txtSetuju = new javax.swing.JCheckBox();
        txtHargaTanah = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 255, 255));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel1.setText("Nomor Pelanggan");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel2.setText("Nama Pemesan");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel3.setText("Area");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel4.setText("Harga Tanah");

        jNopelanggan.setEditable(false);

        cmbArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih", "Bougenville", "Melati", "Flamboyan" }));
        cmbArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbAreaActionPerformed(evt);
            }
        });

        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/penjualan_rumah/1.jpg"))); // NOI18N
        gambar.setEnabled(false);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel6.setText("Harga Bangunan");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel7.setText("Tipe Rumah");

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Luas Tanah Asli");

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Luas Tanah Tersedia");

        RBTipe1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RBTipe1.setText("Tipe - 01");
        RBTipe1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTipe1ActionPerformed(evt);
            }
        });

        RBTipe24.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RBTipe24.setText("Tipe - 24");
        RBTipe24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTipe24ActionPerformed(evt);
            }
        });

        RBTipe30.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        RBTipe30.setText("Tipe - 30");
        RBTipe30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBTipe30ActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel10.setText("Harga");

        jLabel11.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel11.setText("DP");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel12.setText("Lama Cicilan");

        jLabel13.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel13.setText("PPN(10%)");

        jLabel14.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel14.setText("Cicilan/Bulan");

        jLabel15.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jLabel15.setText("Bulan");

        txtHargaBangunan.setEditable(false);

        txtLuasAsli.setEditable(false);

        txtHarga.setEditable(false);

        txtPpn.setEditable(false);

        txtCicilan.setEditable(false);

        BProses.setText("PROSES");
        BProses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BProsesActionPerformed(evt);
            }
        });

        jSimpan.setText("SIMPAN");
        jSimpan.setEnabled(false);
        jSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSimpanActionPerformed(evt);
            }
        });

        jButton3.setText("HAPUS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        txtSetuju.setText("SETUJU");
        txtSetuju.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSetujuActionPerformed(evt);
            }
        });

        txtHargaTanah.setEditable(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(65, 65, 65)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jNopelanggan)
                                    .addComponent(txtNama, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(gambar)))
                        .addGap(93, 93, 93)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(RBTipe1)
                                    .addComponent(RBTipe24)
                                    .addComponent(RBTipe30)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel14))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel9)
                                                .addComponent(jLabel8))
                                            .addComponent(txtLuasTersedia, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtLuasAsli, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtHarga, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtDp, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPpn, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtCicilan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtSetuju))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel15))))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(BProses, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jNopelanggan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtHargaBangunan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(cmbArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBTipe1)
                            .addComponent(txtHargaTanah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(txtLuasAsli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gambar)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBTipe24)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBTipe30)
                            .addComponent(txtLuasTersedia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtHarga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtDp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15)
                            .addComponent(txtPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(txtPpn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtCicilan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSetuju)))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BProses, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(70, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void cmbAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbAreaActionPerformed
    if (cmbArea.getSelectedIndex()==0){
        txtHargaTanah.setText("");
        txtHargaBangunan.setText("");
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("")));
        gambar.setEnabled(false);
        area = null;
    }
    else if (cmbArea.getSelectedIndex()==1){
        txtHargaTanah.setText("500000");
        txtHargaBangunan.setText("90000000");
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("1.jpg")));
        gambar.setEnabled(true);
        area = "Bougenville";
    }
    else if(cmbArea.getSelectedIndex()==2){
        txtHargaTanah.setText("600000");
        txtHargaBangunan.setText("120000000");
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("2.jpg")));
        gambar.setEnabled(true);
        area = "Melati";
    }
    else{
        txtHargaTanah.setText("700000");
        txtHargaBangunan.setText("150000000");
        gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("3.JPG")));
        gambar.setEnabled(true);
        area = "Flamboyan";
    }
    }//GEN-LAST:event_cmbAreaActionPerformed

    private void RBTipe1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTipe1ActionPerformed
     txtLuasAsli.setText("90");
     txtLuasTersedia.setText("90");
     tipe = "Tipe-01";
    }//GEN-LAST:event_RBTipe1ActionPerformed

    private void RBTipe24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTipe24ActionPerformed
      txtLuasAsli.setText("120");
      txtLuasTersedia.setText("120");
      tipe = "Tipe-24";
    }//GEN-LAST:event_RBTipe24ActionPerformed

    private void RBTipe30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBTipe30ActionPerformed
        txtLuasAsli.setText("140");
        txtLuasTersedia.setText("140");
        tipe = "Tipe-30";
    }//GEN-LAST:event_RBTipe30ActionPerformed

    private void BProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BProsesActionPerformed
        RandomID();
        jNopelanggan.setText(""+no_pelanggan);
        txtSetuju.setEnabled(true);
        Ltersedia = Integer.parseInt(txtLuasTersedia.getText());
        Htanah = Integer.parseInt(txtHargaTanah.getText());
        Hbangunan = Integer.parseInt(txtHargaBangunan.getText());
        int tanah = Htanah*Ltersedia;
        int tot = tanah+Hbangunan;
        txtHarga.setText(""+tot);
        int nPpn = tot/100*10;
        txtPpn.setText(""+nPpn);
        nDp = Integer.parseInt(txtDp.getText());
        int bayar = tot+nPpn-nDp;
        nPeriode = Integer.parseInt(txtPeriode.getText());
        int nBulan = nPeriode;
        int nCicilan = bayar/nBulan;
        txtCicilan.setText(""+nCicilan);
    }//GEN-LAST:event_BProsesActionPerformed

    private void txtSetujuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSetujuActionPerformed
     if (txtSetuju.isSelected()){
         JOptionPane.showMessageDialog(null, "PELANGGAN KONFIRM/SETUJU","KOTAK KONFIRMASI", JOptionPane.INFORMATION_MESSAGE);
         jSimpan.setEnabled(true);
     }else{
         jSimpan.setEnabled(false);
     }
    }//GEN-LAST:event_txtSetujuActionPerformed

    private void jSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSimpanActionPerformed
        try {
            Connection conn = Koneksi.getConnection();
            PreparedStatement stmt = conn.prepareStatement("INSERT INTO "
                    +"tabeldata(nama, area, harga_tanah, harga_bangunan, "
                    +"tipe_rumah, luas_tanah_a, luas_tanah_t, harga, dp, periode ,ppn, cicilan, no_pelanggan)"
                    +"values(?,?,?,?,?,?,?,?,?,?,?,?,?)");
            
            stmt.setString(1, txtNama.getText());
            stmt.setString(2, area);
            stmt.setString(3, txtHargaTanah.getText());
            stmt.setString(4, txtHargaBangunan.getText());
            stmt.setString(5, tipe);
            stmt.setString(6, txtLuasAsli.getText());
            stmt.setString(7, txtLuasTersedia.getText());
            stmt.setString(8, txtHarga.getText());
            stmt.setString(9, txtDp.getText());
            stmt.setString(10, txtPeriode.getText());
            stmt.setString(11, txtPpn.getText());
            stmt.setString(12, txtCicilan.getText());
            stmt.setString(13, no_pelanggan);

            stmt.executeUpdate();
            no_pelanggan = "";
            jNopelanggan.setText("");
            txtNama.setText("");
            cmbArea.setSelectedIndex(0);
            txtHargaTanah.setText("");
            txtHargaBangunan.setText("");
            RBTipe1.setSelected(false);
            RBTipe24.setSelected(false);
            RBTipe30.setSelected(false);
            txtLuasAsli.setText("");
            txtLuasTersedia.setText("");
            txtHarga.setText("");
            txtDp.setText("");
            txtPeriode.setText("");
            txtPpn.setText("");
            txtCicilan.setText("");
            txtSetuju.setSelected(false);
            txtSetuju.setEnabled(false);
            JOptionPane.showMessageDialog(this, "Berhasil!");
        }catch(SQLException e){
            JOptionPane.showMessageDialog(this, e);
            System.out.print(e);
        }
    }//GEN-LAST:event_jSimpanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIPenjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JIPenjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BProses;
    private javax.swing.JRadioButton RBTipe1;
    private javax.swing.JRadioButton RBTipe24;
    private javax.swing.JRadioButton RBTipe30;
    private javax.swing.JComboBox<String> cmbArea;
    private javax.swing.JLabel gambar;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jNopelanggan;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSimpan;
    private javax.swing.JTextField txtCicilan;
    private javax.swing.JTextField txtDp;
    private javax.swing.JTextField txtHarga;
    private javax.swing.JTextField txtHargaBangunan;
    private javax.swing.JTextField txtHargaTanah;
    private javax.swing.JTextField txtLuasAsli;
    private javax.swing.JTextField txtLuasTersedia;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtPeriode;
    private javax.swing.JTextField txtPpn;
    private javax.swing.JCheckBox txtSetuju;
    // End of variables declaration//GEN-END:variables

    private void Checker() {
            Connection conn = Koneksi.getConnection();
     try{
        java.sql.Statement stmt = conn.createStatement();
   
        java.sql.ResultSet res = stmt.executeQuery(SQL);
         if (res.next()){
         if(res.getInt("jml")==0){
              no_pelanggan = "P000001";
       }else{
             kode = res.getInt("id")+1;
              String xd = Integer.toString(kode);
               String Nol = "";
         if(xd.length()==1){
               Nol = "00000";
          }else if(xd.length()==2){
                 Nol = "0000";
                 }else if(xd.length()==3){
                     Nol = "000";
                 }else if(xd.length()==4){
                    Nol = "00";
                 }else if(xd.length()==5){
                     Nol = "0";
                 }else{
                    Nol = "";
                 }
                 no_pelanggan = "p"+Nol+""+kode;
             }
         }
     } catch (SQLException e){
         System.out.println(e.getMessage());
     }
    }
    
       private void RandomID() {
        Random angkaRandom = new Random(); //objek random
        for (int i = 0; i < 5; i++ ){
        RandomA = (char) (angkaRandom.nextInt(26)+'A');
        System.out.print(RandomA);
    }
    for (int i = 0; i  < 5; i++){
    RandomB = angkaRandom.nextInt(100) + 1;
    System.out.print(RandomB);
}
    no_pelanggan = "P_" + RandomA + "_"+ RandomB;
}
}


